import '../shared/styles/EquipmentPrimitives.css'
import '../shared/styles/EquipmentSheetPrimitives.css'
import { EquipmentProfile } from '../../EquipmentProfile'
import { EquipmentEditFormContent } from '../shared/EquipmentEditFormContent'
import { EquipmentTableHeaderCell, EquipmentTableValue } from '../shared/EquipmentTablePrimitives'
import { COLUMNS, defaultVisibleColumns, statusLabel, useEquipmentPanelController } from '../shared/useEquipmentPanelController'

const MOBILE_IDENTITY_KEYS = new Set(['equipmentId','equipmentName','status'])

export function EquipmentMobilePanel() {
  const c = useEquipmentPanelController()
  const visibleCardColumns = COLUMNS.filter((column)=>c.visibleColumns.includes(column.key)&&!MOBILE_IDENTITY_KEYS.has(column.key))

  return <div className="equipment-page equipment-mobile-panel">
    <header className="equipment-mobile-title"><p className="eyebrow">Danh mục thiết bị</p><h2>Danh sách thiết bị</h2><p>{c.sortedRows.length} / {c.rows.length} thiết bị · mobile dùng thẻ, chế độ sửa hàng loạt giữ bảng trực tiếp.</p></header>
    <section className="equipment-summary" aria-label="Tổng quan thiết bị"><article><span>Tổng thiết bị</span><strong>{c.rows.length}</strong></article><article><span>Thiết bị sản xuất</span><strong>{c.productionCount}</strong></article><article><span>Thiết bị đo kiểm</span><strong>{c.measurementCount}</strong></article></section>
    <section className="equipment-mobile-actions equipment-page-actions" aria-label="Thao tác danh sách">{c.canBulkEdit?<button className={`equipment-bulk-mode-toggle${c.bulkMode?' active':''}`} type="button" onClick={()=>c.bulkMode?c.exitBulkMode():c.setBulkMode(true)}>{c.bulkMode?'Thoát sửa':'Sửa hàng loạt'}</button>:null}<button className="equipment-refresh" type="button" onClick={()=>void c.reloadEquipment(true)} disabled={c.loading||c.bulkSaving}>Làm mới</button></section>
    <section className="equipment-mobile-tools" role="search">
      <label className="equipment-search"><span className="sr-only">Tìm thiết bị</span><input value={c.query} onChange={(event)=>c.setQuery(event.target.value)} placeholder="Tìm trên toàn bộ dữ liệu thiết bị…"/></label>
      <div className="equipment-sheet-tools"><div className="equipment-column-picker" ref={c.columnPickerRef}><button className={c.columnPickerOpen?'active':''} type="button" aria-expanded={c.columnPickerOpen} onClick={()=>{c.setFilterColumn(null);c.setFilterSearch('');c.setColumnPickerOpen((value)=>!value)}}>Cột hiển thị · {c.visibleColumns.length}/{COLUMNS.length}</button>{c.columnPickerOpen?<div className="equipment-column-menu"><header><strong>Ẩn / hiện cột</strong><div><button type="button" onClick={()=>c.setVisibleColumns(COLUMNS.map((column)=>column.key))}>Hiện tất cả</button><button type="button" onClick={()=>c.setVisibleColumns(defaultVisibleColumns())}>Mặc định</button></div></header>{(['Nhận diện','Quản lý','Kỹ thuật','Vòng đời','Tài liệu','Hệ thống'] as const).map((group)=><div key={group}><small>{group}</small>{COLUMNS.filter((column)=>column.group===group).map((column)=><label key={column.key}><input type="checkbox" checked={c.visibleColumns.includes(column.key)} onChange={()=>c.toggleColumn(column.key)}/><span>{column.label}</span></label>)}</div>)}</div>:null}</div><button type="button" className={c.activeFilterCount?'active':''} onClick={()=>c.setColumnFilters({})}>Bỏ toàn bộ lọc{c.activeFilterCount?` · ${c.activeFilterCount}`:''}</button></div>
      {!c.bulkMode?<MobileFilterFields controller={c}/>:null}
    </section>
    {c.bulkMode&&c.canBulkEdit?<div className="equipment-spreadsheet-bar"><div className="equipment-spreadsheet-actions"><button type="button" onClick={()=>c.setInlineChanges({})} disabled={!c.dirtyCount||c.bulkSaving}>Hoàn tác</button><button className="save" type="button" onClick={()=>void c.saveInlineChanges()} disabled={!c.dirtyCount||c.bulkSaving}>{c.bulkSaving?'Đang lưu…':`Lưu ${c.dirtyCount}`}</button><button type="button" onClick={c.exitBulkMode} disabled={c.bulkSaving}>Thoát</button></div></div>:null}
    {c.message?<div className="equipment-feedback" role="status">{c.message}</div>:null}{c.error?<div className="equipment-state error" role="alert">{c.error}</div>:null}{c.loading&&c.rows.length===0?<div className="equipment-state">Đang tải danh mục thiết bị…</div>:null}
    {c.rows.length>0?(c.bulkMode?<MobileBulkTable controller={c}/>:<div className="equipment-mobile-card-list">{c.sortedRows.map((equipment)=>{const photo=c.photos[equipment.equipmentId]||{state:'loading',url:''};const pasteReady=photo.state==='no';return <article className="equipment-mobile-card" key={equipment.equipmentId}><header className="equipment-mobile-card-head"><div className={`equipment-mobile-card-photo${pasteReady?' paste-ready':''}`} tabIndex={pasteReady?0:undefined} onPaste={pasteReady?(event)=>void c.handleEmptyPhotoCellPaste(equipment.equipmentId,event):undefined}>{photo.state==='yes'&&photo.url?<button type="button" onClick={()=>c.setProfileId(equipment.equipmentId)}><img src={photo.url} alt={equipment.equipmentName}/></button>:photo.state==='loading'?<span>…</span>:<button type="button" onClick={()=>c.setProfileId(equipment.equipmentId)}>Chưa có ảnh</button>}</div><button className="equipment-mobile-card-identity" type="button" onClick={()=>c.setProfileId(equipment.equipmentId)}><strong>{equipment.equipmentName}</strong><span>{equipment.equipmentId}</span></button><span className={`equipment-status status-${equipment.status.toLowerCase()}`}>{statusLabel[equipment.status]||equipment.status}</span></header><div className="equipment-mobile-card-fields">{visibleCardColumns.map((column)=><div className="equipment-mobile-card-field" key={column.key}><span>{column.label}</span><div><EquipmentTableValue controller={c} equipment={equipment} column={column}/></div></div>)}</div><footer><button type="button" onClick={()=>c.setProfileId(equipment.equipmentId)}>Hồ sơ</button><button type="button" onClick={()=>c.openEdit(equipment)}>Sửa</button></footer></article>})}</div>):null}
    <MobileOverlays controller={c}/>
  </div>
}

function MobileFilterFields({controller:c}:{controller:ReturnType<typeof useEquipmentPanelController>}) {
  const columns=COLUMNS.filter((column)=>c.visibleColumns.includes(column.key))
  return <div className="equipment-mobile-filter-fields" aria-label="Lọc theo cột">{columns.map((column)=>{const selected=c.columnFilters[column.key]||[];const open=c.filterColumn===column.key;const options=c.filterOptions(column.key).filter((value)=>value.toLocaleLowerCase().includes(c.filterSearch.toLocaleLowerCase()));return <div className="equipment-mobile-filter-field" key={column.key}><button className={selected.length?'active':''} type="button" onClick={()=>{c.setColumnPickerOpen(false);c.setFilterColumn((current)=>current===column.key?null:column.key);c.setFilterSearch('')}}>{column.label}{selected.length?` · ${selected.length}`:''}</button>{open?<div className="equipment-mobile-filter-panel"><input type="search" value={c.filterSearch} onChange={(event)=>c.setFilterSearch(event.target.value)} placeholder={`Tìm trong ${column.label.toLocaleLowerCase()}…`}/><div className="equipment-filter-actions"><button type="button" onClick={()=>c.clearFilter(column.key)}>Bỏ lọc</button><button type="button" onClick={()=>c.setColumnFilters((current)=>({...current,[column.key]:c.filterOptions(column.key)}))}>Chọn tất cả</button></div>{options.map((value)=><label className="equipment-filter-option" key={value}><input type="checkbox" checked={selected.includes(value)} onChange={()=>c.toggleFilterValue(column.key,value)}/><span>{value}</span></label>)}</div>:null}</div>})}</div>
}

function MobileBulkTable({controller:c}:{controller:ReturnType<typeof useEquipmentPanelController>}) {
  return <div className="equipment-mobile-table-scroll"><table className="equipment-data-table spreadsheet-mode"><caption className="sr-only">Danh sách thiết bị sửa trực tiếp</caption><thead><tr><th>Ảnh</th>{COLUMNS.filter((column)=>c.visibleColumns.includes(column.key)).map((column)=><EquipmentTableHeaderCell key={column.key} controller={c} column={column}/>) }<th aria-label="Thao tác"/></tr></thead><tbody>{c.sortedRows.map((equipment)=>{const photo=c.photos[equipment.equipmentId]||{state:'loading',url:''};const dirty=Boolean(c.inlineChanges[equipment.equipmentId]);return <tr key={equipment.equipmentId} className={dirty?'is-dirty':''}><td>{photo.state==='yes'&&photo.url?<button className="equipment-image-button" type="button" onClick={()=>c.setProfileId(equipment.equipmentId)}><img src={photo.url} alt={equipment.equipmentName}/></button>:<span className="equipment-photo-state">{photo.state==='loading'?'…':'—'}</span>}</td>{COLUMNS.filter((column)=>c.visibleColumns.includes(column.key)).map((column)=><td key={column.key}><EquipmentTableValue controller={c} equipment={equipment} column={column}/></td>)}<td><span className={dirty?'equipment-inline-dirty-dot':'equipment-cell-muted'}>{dirty?'Đã sửa':'—'}</span></td></tr>})}</tbody></table></div>
}

function MobileOverlays({controller:c}:{controller:ReturnType<typeof useEquipmentPanelController>}) {
  const editing=c.editing
  return <>
    {c.profileEquipment?<EquipmentProfile equipment={c.profileEquipment} photoUrl={c.photos[c.profileEquipment.equipmentId]?.url||''} onClose={()=>c.setProfileId('')} onEdit={()=>c.openEdit(c.profileEquipment!)}/>:null}
    {editing?<div className="equipment-drawer-backdrop equipment-mobile-drawer-backdrop" onMouseDown={(event)=>{if(event.target===event.currentTarget&&!c.saving&&!c.deleting)c.setEditing(null)}}><section className="equipment-drawer equipment-mobile-drawer" role="dialog" aria-modal="true" aria-labelledby="equipment-drawer-title-mobile"><header><div><p className="eyebrow">Danh mục thiết bị</p><h2 id="equipment-drawer-title-mobile">Chỉnh sửa thiết bị</h2></div><button type="button" onClick={()=>c.setEditing(null)} disabled={c.saving||c.deleting} aria-label="Đóng">×</button></header><EquipmentEditFormContent controller={c}/><footer><button className="equipment-delete" type="button" onClick={()=>void c.handleDelete()} disabled={c.saving||c.deleting}>{c.deleting?'Đang xóa…':'Xóa thiết bị'}</button><div className="equipment-drawer-footer-actions"><button type="button" onClick={()=>c.setEditing(null)} disabled={c.saving||c.deleting}>Hủy</button><button type="button" onClick={()=>void c.handleSave()} disabled={c.saving||c.deleting||!c.editCriticality}>{c.saving?'Đang lưu…':'Lưu thay đổi'}</button></div></footer></section></div>:null}
  </>
}
