import { useEffect, useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import './SpareParts.css'
import { useAppRole } from './auth/AppRoleContext'
import { loadLiveEquipment, type LiveEquipment } from './data/liveEquipment'
import { loadSpareParts, loadSpareUsage, recordSpareUsage, saveSparePart, type LiveSparePart, type SpareClassification, type SpareUsage } from './data/liveSpareParts'

type PartForm = {
  partId: string; partName: string; partNumber: string; maker: string; stockQty: string; minQty: string; location: string; leadTimeDays: string;
  stopsProduction: boolean; qualitySafetyImpact: boolean; leadTimeExceedsRecovery: boolean; rationaleNote: string; equipmentIds: string[]
}

const EMPTY: PartForm = { partId:'',partName:'',partNumber:'',maker:'',stockQty:'0',minQty:'0',location:'',leadTimeDays:'',stopsProduction:false,qualitySafetyImpact:false,leadTimeExceedsRecovery:false,rationaleNote:'',equipmentIds:[] }
const LABEL: Record<SpareClassification,string> = { NORMAL:'Normal', RECOMMENDED:'Recommended', REQUIRED:'Required' }

function classify(form: PartForm, equipment: LiveEquipment[]) {
  const criticalCount=form.equipmentIds.filter((id)=>{const level=(equipment.find((row)=>row.equipmentId===id)?.criticality||'').toUpperCase();return level==='A'||level==='B'}).length
  const sharedCritical=criticalCount>=2
  const score=Number(form.stopsProduction)+Number(form.qualitySafetyImpact)+Number(form.leadTimeExceedsRecovery)+Number(sharedCritical)
  const classification:SpareClassification=form.qualitySafetyImpact||(form.stopsProduction&&form.leadTimeExceedsRecovery)||score>=3?'REQUIRED':score===2?'RECOMMENDED':'NORMAL'
  return {criticalCount,sharedCritical,score,classification}
}

function formFromPart(part: LiveSparePart): PartForm { return { partId:part.partId,partName:part.partName,partNumber:part.partNumber,maker:part.maker,stockQty:String(part.stockQty),minQty:String(part.minQty),location:part.location,leadTimeDays:part.leadTimeDays===null?'':String(part.leadTimeDays),stopsProduction:part.stopsProduction,qualitySafetyImpact:part.qualitySafetyImpact,leadTimeExceedsRecovery:part.leadTimeExceedsRecovery,rationaleNote:part.rationaleNote,equipmentIds:part.equipment.map((item)=>item.equipmentId) } }

export function LiveSparePartsPanel(){
  const role=useAppRole(); const canEdit=['MAINTENANCE','MANAGER','ADMIN'].includes(role)
  const [parts,setParts]=useState<LiveSparePart[]>([]); const [equipment,setEquipment]=useState<LiveEquipment[]>([]); const [usage,setUsage]=useState<SpareUsage[]>([])
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState('')
  const [query,setQuery]=useState(''); const [purchaseOnly,setPurchaseOnly]=useState(false); const [selectedId,setSelectedId]=useState(''); const [editing,setEditing]=useState(false); const [form,setForm]=useState<PartForm>(EMPTY)
  const [equipmentToAdd,setEquipmentToAdd]=useState(''); const [usageEquipment,setUsageEquipment]=useState(''); const [usageQty,setUsageQty]=useState('1'); const [usageReason,setUsageReason]=useState(''); const [usageBy,setUsageBy]=useState('')

  const reload=async()=>{const [p,e]=await Promise.all([loadSpareParts(),loadLiveEquipment()]);setParts(p);setEquipment(e)}
  useEffect(()=>{let active=true;Promise.all([loadSpareParts(),loadLiveEquipment()]).then(([p,e])=>{if(active){setParts(p);setEquipment(e);setError('')}}).catch((cause:unknown)=>{if(active)setError(cause instanceof Error?cause.message:'Không thể tải danh mục phụ tùng')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[])
  const selected=parts.find((item)=>item.partId===selectedId)||null
  useEffect(()=>{if(!selectedId){setUsage([]);return}void loadSpareUsage(selectedId).then(setUsage).catch(()=>setUsage([]))},[selectedId])
  const preview=classify(form,equipment)
  const normalized=query.trim().toLowerCase()
  const filtered=useMemo(()=>parts.filter((part)=>{if(purchaseOnly&&!(part.stockQty<=part.minQty&&part.classification!=='NORMAL'))return false;if(!normalized)return true;return [part.partId,part.partName,part.partNumber,part.maker,part.location,...part.equipment.flatMap((e)=>[e.equipmentId,e.equipmentName])].join(' ').toLowerCase().includes(normalized)}),[parts,purchaseOnly,normalized])
  const required=parts.filter((p)=>p.classification==='REQUIRED').length, needBuy=parts.filter((p)=>p.stockQty<=p.minQty&&p.classification!=='NORMAL').length

  function startNew(){setSelectedId('');setForm(EMPTY);setEditing(true);setMessage('');setError('')}
  function startEdit(part:LiveSparePart){setSelectedId(part.partId);setForm(formFromPart(part));setEditing(true);setMessage('');setError('')}
  function addEquipment(){const id=equipmentToAdd.trim().toUpperCase();if(!id||!equipment.some((e)=>e.equipmentId===id)||form.equipmentIds.includes(id))return;setForm((v)=>({...v,equipmentIds:[...v.equipmentIds,id]}));setEquipmentToAdd('')}
  function removeEquipment(id:string){setForm((v)=>({...v,equipmentIds:v.equipmentIds.filter((item)=>item!==id)}))}

  async function submit(e:FormEvent){e.preventDefault();if(!canEdit)return;setSaving(true);setError('');setMessage('');try{const saved=await saveSparePart({partId:form.partId.trim().toUpperCase(),partName:form.partName.trim(),partNumber:form.partNumber.trim(),maker:form.maker.trim(),stockQty:Math.max(0,Number(form.stockQty)||0),minQty:Math.max(0,Number(form.minQty)||0),location:form.location.trim(),leadTimeDays:form.leadTimeDays===''?null:Math.max(0,Number(form.leadTimeDays)||0),stopsProduction:form.stopsProduction,qualitySafetyImpact:form.qualitySafetyImpact,leadTimeExceedsRecovery:form.leadTimeExceedsRecovery,rationaleNote:form.rationaleNote.trim(),equipmentIds:form.equipmentIds});await reload();setSelectedId(saved.partId);setEditing(false);setMessage(`Đã lưu ${saved.partId} · ${LABEL[saved.classification]} ${saved.riskScore}/4`)}catch(cause:unknown){setError(cause instanceof Error?cause.message:'Không thể lưu phụ tùng')}finally{setSaving(false)}}

  async function submitUsage(e:FormEvent){e.preventDefault();if(!selected||!usageEquipment)return;setSaving(true);setError('');try{await recordSpareUsage({partId:selected.partId,equipmentId:usageEquipment,quantity:Math.max(1,Number(usageQty)||1),reason:usageReason.trim(),performedBy:usageBy.trim()});await reload();setUsage(await loadSpareUsage(selected.partId));setUsageReason('');setUsageQty('1');setMessage(`Đã ghi thay ${selected.partId} cho ${usageEquipment}`)}catch(cause:unknown){setError(cause instanceof Error?cause.message:'Không thể ghi lịch sử thay')}finally{setSaving(false)}}

  return <div className="spare-page">
    <section className="spare-summary"><article><span>Danh mục</span><strong>{parts.length}</strong><small>linh kiện đã biết</small></article><article><span>Required</span><strong>{required}</strong><small>cần bảo đảm khả dụng</small></article><article className={needBuy?'warn':''}><span>Cần xem xét mua</span><strong>{needBuy}</strong><small>tồn ≤ min</small></article><article><span>Mapped</span><strong>{parts.filter((p)=>p.equipmentCount>0).length}</strong><small>đã nối với máy</small></article></section>
    <section className="spare-surface">
      <header className="spare-header"><div><p className="eyebrow">Replacement Parts · IATF 8.5.1.5</p><h2>Linh kiện thay thế</h2><p>Biết máy nào dùng chung, đã thay gì và cái gì cần mua trước.</p></div>{canEdit?<button className="spare-primary" onClick={startNew}>+ Thêm linh kiện</button>:null}</header>
      <div className="spare-toolbar"><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Tìm mã part, tên, máy, maker…"/><label><input type="checkbox" checked={purchaseOnly} onChange={(e)=>setPurchaseOnly(e.target.checked)}/> Chỉ hiện cần mua</label></div>
      {message?<div className="spare-state success">{message}</div>:null}{error?<div className="spare-state error">{error}</div>:null}{loading?<div className="spare-state">Đang tải phụ tùng…</div>:null}
      {!loading?<div className="spare-grid"><div className="spare-list">{filtered.map((part)=><button key={part.partId} className={`spare-card ${selectedId===part.partId?'active':''}`} onClick={()=>{setSelectedId(part.partId);setEditing(false)}}><div><strong>{part.partName}</strong><small>{part.partId}{part.partNumber?` · ${part.partNumber}`:''}</small></div><span className={`spare-badge ${part.classification.toLowerCase()}`}>{LABEL[part.classification]} {part.riskScore}/4</span><div className="spare-card-meta"><span>{part.equipmentCount} máy</span><span>Tồn {part.stockQty} / Min {part.minQty}</span>{part.stockQty<=part.minQty&&part.classification!=='NORMAL'?<b>Cần mua</b>:null}</div></button>)}{!filtered.length?<p className="spare-empty">Chưa có dữ liệu phù hợp.</p>:null}</div>
        <div className="spare-detail">{editing?<form onSubmit={submit} className="spare-form"><header><div><p className="eyebrow">Đánh giá tự động</p><h3>{form.partId||'Linh kiện mới'}</h3></div><span className={`spare-badge ${preview.classification.toLowerCase()}`}>{LABEL[preview.classification]} {preview.score}/4</span></header><div className="spare-fields"><label><span>Mã quản lý *</span><input value={form.partId} disabled={Boolean(selectedId)} onChange={(e)=>setForm({...form,partId:e.target.value.toUpperCase()})} placeholder="SP-0001" required/></label><label><span>Tên linh kiện *</span><input value={form.partName} onChange={(e)=>setForm({...form,partName:e.target.value})} required/></label><label><span>Part No.</span><input value={form.partNumber} onChange={(e)=>setForm({...form,partNumber:e.target.value})}/></label><label><span>Maker</span><input value={form.maker} onChange={(e)=>setForm({...form,maker:e.target.value})}/></label><label><span>Tồn hiện tại</span><input type="number" min="0" value={form.stockQty} onChange={(e)=>setForm({...form,stockQty:e.target.value})}/></label><label><span>Min Qty</span><input type="number" min="0" value={form.minQty} onChange={(e)=>setForm({...form,minQty:e.target.value})}/></label><label><span>Vị trí</span><input value={form.location} onChange={(e)=>setForm({...form,location:e.target.value})}/></label><label><span>Lead time (ngày)</span><input type="number" min="0" value={form.leadTimeDays} onChange={(e)=>setForm({...form,leadTimeDays:e.target.value})}/></label></div>
          <section className="spare-risk"><h4>4 yếu tố xác định</h4><label><input type="checkbox" checked={form.stopsProduction} onChange={(e)=>setForm({...form,stopsProduction:e.target.checked})}/><span><b>1. Hỏng part làm máy/line dừng?</b><small>Điểm do TAN xác nhận.</small></span></label><label><input type="checkbox" checked={form.qualitySafetyImpact} onChange={(e)=>setForm({...form,qualitySafetyImpact:e.target.checked})}/><span><b>2. Ảnh hưởng chất lượng hoặc an toàn?</b><small>Có → hệ thống tự xếp Required.</small></span></label><label><input type="checkbox" checked={form.leadTimeExceedsRecovery} onChange={(e)=>setForm({...form,leadTimeExceedsRecovery:e.target.checked})}/><span><b>3. Lead time dài hơn thời gian dừng chấp nhận?</b><small>Ghi lead time phía trên làm căn cứ.</small></span></label><label className="auto"><input type="checkbox" checked={preview.sharedCritical} readOnly/><span><b>4. Dùng chung ≥2 máy A/B?</b><small>Hệ thống tự tính · hiện có {preview.criticalCount} máy A/B.</small></span></label></section>
          <section className="spare-equipment-editor"><h4>Máy sử dụng</h4><div className="spare-add-row"><input list="spare-equipment-options" value={equipmentToAdd} onChange={(e)=>setEquipmentToAdd(e.target.value)} placeholder="Nhập mã máy…"/><datalist id="spare-equipment-options">{equipment.map((e)=><option key={e.equipmentId} value={e.equipmentId}>{e.equipmentName}</option>)}</datalist><button type="button" onClick={addEquipment}>Thêm</button></div><div className="spare-chips">{form.equipmentIds.map((id)=>{const row=equipment.find((e)=>e.equipmentId===id);return <button type="button" key={id} onClick={()=>removeEquipment(id)}>{id} <small>{row?.criticality||'—'}</small> ×</button>})}</div></section>
          <label className="spare-note"><span>Căn cứ / ghi chú</span><textarea value={form.rationaleNote} onChange={(e)=>setForm({...form,rationaleNote:e.target.value})} placeholder="Ví dụ: 3 máy A dùng chung, lead time 45 ngày, dừng line nếu không có…"/></label><footer><button type="button" onClick={()=>setEditing(false)}>Hủy</button><button className="spare-primary" disabled={saving}>{saving?'Đang lưu…':'Lưu & tự phân loại'}</button></footer></form>:selected?<><header className="spare-detail-head"><div><p className="eyebrow">{selected.partId}</p><h3>{selected.partName}</h3><p>{selected.partNumber||'Chưa có Part No.'}{selected.maker?` · ${selected.maker}`:''}</p></div><span className={`spare-badge ${selected.classification.toLowerCase()}`}>{LABEL[selected.classification]} {selected.riskScore}/4</span></header><div className="spare-facts"><div><span>Tồn / Min</span><strong>{selected.stockQty} / {selected.minQty}</strong></div><div><span>Vị trí</span><strong>{selected.location||'—'}</strong></div><div><span>Lead time</span><strong>{selected.leadTimeDays===null?'—':`${selected.leadTimeDays} ngày`}</strong></div><div><span>Dùng cho</span><strong>{selected.equipmentCount} máy</strong></div></div><section className="spare-why"><h4>Vì sao hệ thống xếp {LABEL[selected.classification]}?</h4><p className={selected.stopsProduction?'yes':''}>{selected.stopsProduction?'✓':'○'} Dừng máy/line</p><p className={selected.qualitySafetyImpact?'yes':''}>{selected.qualitySafetyImpact?'✓':'○'} Ảnh hưởng chất lượng/an toàn</p><p className={selected.leadTimeExceedsRecovery?'yes':''}>{selected.leadTimeExceedsRecovery?'✓':'○'} Lead time vượt recovery</p><p className={selected.sharedCritical?'yes':''}>{selected.sharedCritical?'✓':'○'} Dùng chung ≥2 máy A/B ({selected.criticalEquipmentCount})</p>{selected.rationaleNote?<blockquote>{selected.rationaleNote}</blockquote>:null}</section><section><h4>Máy sử dụng</h4><div className="spare-equipment-list">{selected.equipment.map((e)=><div key={e.equipmentId}><b>{e.equipmentId}</b><span>{e.equipmentName}</span><small>Cấp {e.criticality||'—'}</small></div>)}</div></section>{canEdit?<div className="spare-actions"><button className="spare-primary" onClick={()=>startEdit(selected)}>Đánh giá / sửa</button></div>:null}
          <section className="spare-usage"><h4>Lịch sử thay</h4>{canEdit?<form onSubmit={submitUsage} className="spare-usage-form"><select value={usageEquipment} onChange={(e)=>setUsageEquipment(e.target.value)} required><option value="">Chọn máy…</option>{selected.equipment.map((e)=><option key={e.equipmentId} value={e.equipmentId}>{e.equipmentId} · {e.equipmentName}</option>)}</select><input type="number" min="1" value={usageQty} onChange={(e)=>setUsageQty(e.target.value)} aria-label="Số lượng"/><input value={usageBy} onChange={(e)=>setUsageBy(e.target.value)} placeholder="Ai thay? Production / TAN / Vendor"/><input value={usageReason} onChange={(e)=>setUsageReason(e.target.value)} placeholder="Lý do / sự cố"/><button disabled={saving}>Ghi đã thay</button></form>:null}<div className="spare-usage-list">{usage.map((u)=><article key={u.usageId}><b>{u.equipmentId} × {u.quantity}</b><span>{new Date(u.usedAt).toLocaleString('vi-VN')}</span><small>{u.reason||'Không ghi lý do'} · {u.performedBy||u.actorEmail||'—'}</small></article>)}{!usage.length?<p>Chưa có lịch sử thay.</p>:null}</div></section></>:<div className="spare-placeholder"><strong>Chọn một linh kiện</strong><p>Xem máy dùng chung, lý do phân loại và lịch sử thay.</p></div>}</div></div>:null}
    </section>
  </div>
}
