import { useEffect, useState } from 'react'
import './Calibration.css'
import { canRecordCalibration, useAppRole } from './auth/AppRoleContext'
import { evaluateCalibration, getCalibrationEvaluationSnapshot, loadCalibrationEvaluations, type CalibrationEvaluationRow } from './data/liveCalibrationEvaluation'

const resultLabel:Record<string,string>={PASS:'Đạt',FAIL:'Không đạt',LIMITED_USE:'Sử dụng hạn chế'}
const roleLabel:Record<string,string>={MAINTENANCE:'Bảo trì',SUPERVISOR:'Giám sát',QUALITY:'Chất lượng',MANAGER:'Quản lý',ADMIN:'Quản trị hệ thống',UNKNOWN:'Chưa xác định'}

export function LiveCalibrationEvaluationPanel(){
  const role=useAppRole(); const canEvaluate=canRecordCalibration(role)
  const [rows,setRows]=useState<CalibrationEvaluationRow[]>(()=>getCalibrationEvaluationSnapshot()); const [selected,setSelected]=useState<CalibrationEvaluationRow|null>(null)
  const [result,setResult]=useState<'PASS'|'FAIL'|'LIMITED_USE'>('PASS'); const [note,setNote]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState('')
  useEffect(()=>{let active=true;void loadCalibrationEvaluations().then((next)=>{if(!active)return;setRows(next);setError('')}).catch((e)=>{if(active)setError(e instanceof Error?e.message:'Không tải được dữ liệu đánh giá')});return()=>{active=false}},[])
  const pending=rows.filter((r)=>!r.evaluationResult), done=rows.filter((r)=>r.evaluationResult)
  const submit=async()=>{if(!selected||!canEvaluate)return;if(result!=='PASS'&&!note.trim()){setError('Kết quả Không đạt / Sử dụng hạn chế bắt buộc ghi lý do đánh giá.');return}setBusy(true);setError('');setMessage('');try{await evaluateCalibration({calibrationLogId:selected.calibrationLogId,equipmentId:selected.equipmentId,result,note});setRows(getCalibrationEvaluationSnapshot());setMessage(`Đã đánh giá ${selected.calibrationLogId}: ${resultLabel[result]}`);setSelected(null);setNote('');setResult('PASS')}catch(e){setError(e instanceof Error?e.message:'Không thể đánh giá')}finally{setBusy(false)}}
  return <section className="calibration-surface"><header className="calibration-header"><div><p className="eyebrow">Đánh giá sau hiệu chuẩn</p><h2>Đánh giá sau hiệu chuẩn</h2><p>Mỗi bản ghi hiệu chuẩn chỉ được đánh giá một lần để bảo đảm truy vết.</p></div><span className="calibration-link-state link-linked">{pending.length} chờ đánh giá</span></header>
    {message?<div className="calibration-state success">{message}</div>:null}{error?<div className="calibration-state error">{error}</div>:null}
    {pending.length?<div className="calibration-table-scroll"><table className="calibration-table"><thead><tr><th>Mã bản ghi</th><th>Thiết bị</th><th>Ngày</th><th>Kết quả hiệu chuẩn</th><th>Đơn vị</th><th /></tr></thead><tbody>{pending.map((row)=><tr key={row.calibrationLogId}><td><b>{row.calibrationLogId}</b></td><td>{row.equipmentId}</td><td>{row.calibrationDate}</td><td>{resultLabel[row.calibrationResult]||row.calibrationResult}</td><td>{row.provider||'—'}</td><td>{canEvaluate?<button className="calibration-row-action" onClick={()=>{setSelected(row);setResult('PASS');setNote('')}}>Đánh giá</button>:<span className="calibration-readonly">{roleLabel[role]||role}</span>}</td></tr>)}</tbody></table></div>:<div className="calibration-state success">Không có bản ghi hiệu chuẩn chờ đánh giá.</div>}
    {done.length?<details className="calibration-detail-section"><summary>Lịch sử đã đánh giá ({done.length})</summary><div className="calibration-log-list">{done.slice(0,30).map((row)=><article key={row.calibrationLogId}><div><b>{row.equipmentId} · {row.calibrationDate}</b><span>{resultLabel[row.evaluationResult]||row.evaluationResult}</span></div><small>{row.evaluatedBy||'—'} · {row.evaluatedAt?new Date(row.evaluatedAt).toLocaleString('vi-VN'):'—'}</small>{row.evaluationNote?<p>{row.evaluationNote}</p>:null}</article>)}</div></details>:null}
    {selected&&canEvaluate?<div className="calibration-layer" onMouseDown={(e)=>{if(e.target===e.currentTarget)setSelected(null)}}><aside className="calibration-drawer" role="dialog" aria-modal="true"><header><div><p className="eyebrow">Đánh giá sau hiệu chuẩn</p><h2>{selected.equipmentId}</h2><p>{selected.calibrationLogId} · {selected.calibrationDate}</p></div><button onClick={()=>setSelected(null)}>×</button></header><div className="calibration-detail-grid"><div><span>Kết quả hiệu chuẩn</span><strong>{resultLabel[selected.calibrationResult]||selected.calibrationResult}</strong></div><div><span>Đơn vị</span><strong>{selected.provider||'—'}</strong></div></div><div className="calibration-record-form"><label><span>Đánh giá</span><select value={result} onChange={(e)=>setResult(e.target.value as typeof result)}><option value="PASS">Đạt</option><option value="LIMITED_USE">Sử dụng hạn chế</option><option value="FAIL">Không đạt</option></select></label><label><span>Ghi chú đánh giá</span><textarea value={note} onChange={(e)=>setNote(e.target.value)} placeholder={result==='PASS'?'Có thể để trống':'Bắt buộc nêu lý do / giới hạn sử dụng'}/></label><button className="calibration-record-button primary" disabled={busy} onClick={()=>void submit()}>{busy?'Đang lưu…':'Xác nhận đánh giá'}</button></div></aside></div>:null}
  </section>
}
