import { useEffect, useMemo, useState, type FormEvent } from 'react'
import './Calibration.css'
import { canRecordCalibration, useAppRole } from './auth/AppRoleContext'
import { loadLiveCalibration, type LiveCalibration } from './data/liveCalibration'
import { supabase } from './data/supabaseClient'

type QuoteRow={quoteId:string;equipmentId:string;calibrationEquipmentId:string;provider:string;amountVnd:number;sourceDate:string;sourceDocument:string;createdAt:string}
function text(v:unknown){return v==null?'':String(v).trim()}
function amount(v:unknown){const n=Number(v);return Number.isFinite(n)?n:0}
async function loadQuotes():Promise<QuoteRow[]>{const{data,error}=await supabase.from('calibration_vendor_quote').select('*').order('created_at',{ascending:false});if(error)throw error;return((data||[])as Array<Record<string,unknown>>).map((row)=>{const s=(row.source_data as Record<string,unknown>|null)||{};return{quoteId:text(row.quote_id),equipmentId:text(row.equipment_id),calibrationEquipmentId:text(s.calibrationEquipmentId),provider:text(s.provider),amountVnd:amount(s.amountVnd),sourceDate:text(s.sourceDate),sourceDocument:text(s.sourceDocument),createdAt:text(row.created_at)}})}

export function LiveCalibrationQuotePanel(){
  const role=useAppRole();const canWrite=canRecordCalibration(role)
  const[masters,setMasters]=useState<LiveCalibration[]>([]);const[quotes,setQuotes]=useState<QuoteRow[]>([]);const[open,setOpen]=useState(false);const[calibrationId,setCalibrationId]=useState('');const[provider,setProvider]=useState('');const[amountVnd,setAmountVnd]=useState('');const[sourceDate,setSourceDate]=useState(new Date().toISOString().slice(0,10));const[sourceDocument,setSourceDocument]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('')
  const refresh=async()=>{const[m,q]=await Promise.all([loadLiveCalibration(),loadQuotes()]);setMasters(m.filter((r)=>r.linkState==='LINKED'));setQuotes(q);setError('')}
  useEffect(()=>{void refresh().catch((e)=>setError(e instanceof Error?e.message:'Không tải được báo giá'))},[])
  const summaries=useMemo(()=>{const map=new Map<string,{provider:string;sourceDate:string;itemCount:number;subtotal:number}>();for(const q of quotes){const key=`${q.provider}|${q.sourceDate}`;const c=map.get(key)||{provider:q.provider,sourceDate:q.sourceDate,itemCount:0,subtotal:0};c.itemCount++;c.subtotal+=q.amountVnd;map.set(key,c)}return[...map.values()].sort((a,b)=>b.sourceDate.localeCompare(a.sourceDate)||a.provider.localeCompare(b.provider))},[quotes])
  const submit=async(e:FormEvent)=>{e.preventDefault();if(!canWrite)return;const value=Number(amountVnd);if(!Number.isInteger(value)||value<0){setError('Số tiền phải là VND nguyên không âm.');return}setBusy(true);setError('');setMessage('');try{const{data,error:rpcError}=await supabase.rpc('rpc_record_calibration_vendor_quote',{p_input:{calibrationEquipmentId:calibrationId,provider:provider.trim(),amountVnd:value,sourceDate,sourceDocument:sourceDocument.trim()}});if(rpcError)throw rpcError;const r=data as Record<string,unknown>;setMessage(`Đã lưu ${text(r.quoteId)}`);setOpen(false);setProvider('');setAmountVnd('');setSourceDocument('');await refresh()}catch(err){setError(err instanceof Error?err.message:'Không thể lưu báo giá')}finally{setBusy(false)}}
  return <section className="calibration-surface"><header className="calibration-header"><div><p className="eyebrow">Calibration Vendor Quote History</p><h2>Lịch sử báo giá hiệu chuẩn</h2><p>Giữ snapshot lịch sử; không biến giá nguồn thành giá live.</p></div>{canWrite?<button onClick={()=>{setOpen(true);setCalibrationId(masters[0]?.calibrationEquipmentId||'')}}>+ Ghi báo giá</button>:<span className="calibration-readonly">Chỉ xem · {role}</span>}</header>
    {message?<div className="calibration-state success">{message}</div>:null}{error?<div className="calibration-state error">{error}</div>:null}
    {summaries.length?<div className="calibration-summary">{summaries.slice(0,4).map((s)=><article key={`${s.provider}-${s.sourceDate}`}><span>{s.provider}</span><strong>{s.subtotal.toLocaleString('vi-VN')} ₫</strong><small>{s.sourceDate} · {s.itemCount} hạng mục</small></article>)}</div>:null}
    {quotes.length?<div className="calibration-table-scroll"><table className="calibration-table"><thead><tr><th>Ngày nguồn</th><th>Calibration ID</th><th>Equipment</th><th>Nhà cung cấp</th><th>Số tiền</th><th>Tài liệu nguồn</th></tr></thead><tbody>{quotes.map((q)=><tr key={q.quoteId}><td>{q.sourceDate}</td><td><b>{q.calibrationEquipmentId}</b><small>{q.quoteId}</small></td><td>{q.equipmentId||'—'}</td><td>{q.provider}</td><td><b>{q.amountVnd.toLocaleString('vi-VN')} ₫</b></td><td>{q.sourceDocument}</td></tr>)}</tbody></table></div>:<div className="calibration-state">Chưa có lịch sử báo giá.</div>}
    {open&&canWrite?<div className="calibration-layer" onMouseDown={(e)=>{if(e.target===e.currentTarget)setOpen(false)}}><aside className="calibration-drawer" role="dialog" aria-modal="true"><header><div><p className="eyebrow">Source Snapshot</p><h2>Ghi báo giá hiệu chuẩn</h2></div><button onClick={()=>setOpen(false)}>×</button></header><form className="calibration-record-form" onSubmit={submit}><label><span>Calibration ID</span><select required value={calibrationId} onChange={(e)=>setCalibrationId(e.target.value)}><option value="">Chọn thiết bị</option>{masters.map((m)=><option key={m.calibrationEquipmentId} value={m.calibrationEquipmentId}>{m.calibrationEquipmentId} · {m.equipmentId} · {m.instrumentName}</option>)}</select></label><label><span>Nhà cung cấp</span><input required value={provider} onChange={(e)=>setProvider(e.target.value)}/></label><label><span>Số tiền VND</span><input type="number" min="0" step="1" required value={amountVnd} onChange={(e)=>setAmountVnd(e.target.value)}/></label><label><span>Ngày tài liệu nguồn</span><input type="date" required value={sourceDate} onChange={(e)=>setSourceDate(e.target.value)}/></label><label><span>Tài liệu nguồn</span><input required value={sourceDocument} onChange={(e)=>setSourceDocument(e.target.value)} placeholder="Tên file / số báo giá / nguồn"/></label><button className="calibration-record-button primary" disabled={busy}>{busy?'Đang lưu…':'Lưu snapshot báo giá'}</button></form></aside></div>:null}
  </section>
}
