import { useEffect, useMemo, useState } from 'react'
import './OrgManagementPanel.css'
import { appointRole, loadOrgAdminData, saveOrgPerson, saveOrgRole, saveOrgUnit, setPersonActive, type OrgPerson, type OrgRole, type OrgRoleAssignment, type OrgUnit } from './data/orgAdmin'

type Tab='people'|'roles'|'units'
const emptyPerson:OrgPerson={person_code:'',display_name:'',unit_code:null,job_title:null,active:true}
const emptyRole:OrgRole={role_code:'',role_name:'',unit_code:null,active:true}
const emptyUnit:OrgUnit={unit_code:'',unit_name:'',unit_type:'DEPARTMENT',parent_unit_code:null,active:true,sort_order:0}

export function OrgManagementPanel(){
  const[tab,setTab]=useState<Tab>('people')
  const[units,setUnits]=useState<OrgUnit[]>([]); const[people,setPeople]=useState<OrgPerson[]>([]); const[roles,setRoles]=useState<OrgRole[]>([]); const[assignments,setAssignments]=useState<OrgRoleAssignment[]>([])
  const[loading,setLoading]=useState(true); const[saving,setSaving]=useState(false); const[message,setMessage]=useState('')
  const[person,setPerson]=useState<OrgPerson>(emptyPerson); const[role,setRole]=useState<OrgRole>(emptyRole); const[unit,setUnit]=useState<OrgUnit>(emptyUnit)
  async function reload(){setLoading(true);try{const data=await loadOrgAdminData();setUnits(data.units);setPeople(data.people);setRoles(data.roles);setAssignments(data.assignments);setMessage('')}catch(error){setMessage(error instanceof Error?error.message:'Không tải được dữ liệu tổ chức')}finally{setLoading(false)}}
  useEffect(()=>{void reload()},[])
  const unitName=useMemo(()=>new Map(units.map((item)=>[item.unit_code,item.unit_name])),[units])
  const personName=useMemo(()=>new Map(people.map((item)=>[item.person_code,item.display_name])),[people])
  const currentAssignment=useMemo(()=>new Map(assignments.filter((item)=>item.active&&!item.valid_to).map((item)=>[item.role_code,item])),[assignments])
  async function run(action:()=>Promise<void>,success:string){setSaving(true);setMessage('');try{await action();setMessage(success);await reload()}catch(error){setMessage(error instanceof Error?error.message:'Không lưu được')}finally{setSaving(false)}}
  function codeFromName(value:string,prefix:string){return `${prefix}_${value.trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'_').replace(/^_+|_+$/g,'').toUpperCase()}`}
  return <section className="org-panel">
    <header className="org-panel-header"><div><p className="eyebrow">Organization master</p><h1>Tổ chức & nhân sự</h1><p>Quản lý bộ phận, nhân sự và chức vụ chịu trách nhiệm thiết bị. Đổi người giữ chức vụ sẽ tự áp dụng cho các thiết bị gắn theo role.</p></div><button type="button" onClick={()=>void reload()} disabled={loading||saving}>Làm mới</button></header>
    <div className="org-tabs" role="tablist"><button className={tab==='people'?'active':''} onClick={()=>setTab('people')}>Nhân sự · {people.length}</button><button className={tab==='roles'?'active':''} onClick={()=>setTab('roles')}>Chức vụ · {roles.length}</button><button className={tab==='units'?'active':''} onClick={()=>setTab('units')}>Bộ phận · {units.length}</button></div>
    {message?<div className="org-message" role="status">{message}</div>:null}
    {loading?<div className="org-loading">Đang tải sơ đồ tổ chức…</div>:null}
    {!loading&&tab==='people'?<div className="org-layout"><div className="org-card"><div className="org-card-title"><h2>Danh sách nhân sự</h2><button onClick={()=>setPerson({...emptyPerson})}>+ Thêm người</button></div><div className="org-table-wrap"><table><thead><tr><th>Người</th><th>Bộ phận</th><th>Chức danh</th><th>Trạng thái</th><th></th></tr></thead><tbody>{people.map((item)=><tr key={item.person_code} className={!item.active?'muted':''}><td><strong>{item.display_name}</strong><small>{item.person_code}</small></td><td>{item.unit_code?unitName.get(item.unit_code)||item.unit_code:'—'}</td><td>{item.job_title||'—'}</td><td>{item.active?'Đang làm việc':'Ngừng'}</td><td><button onClick={()=>setPerson({...item})}>Sửa</button><button onClick={()=>void run(()=>setPersonActive(item.person_code,!item.active),item.active?'Đã ngừng nhân sự':'Đã kích hoạt nhân sự')}>{item.active?'Nghỉ việc':'Kích hoạt'}</button></td></tr>)}</tbody></table></div></div><form className="org-card org-form" onSubmit={(event)=>{event.preventDefault();const next={...person,person_code:person.person_code||codeFromName(person.display_name,'P')};void run(()=>saveOrgPerson(next),'Đã lưu nhân sự');setPerson(emptyPerson)}}><h2>{person.person_code?'Cập nhật nhân sự':'Thêm nhân sự'}</h2><label>Tên hiển thị<input value={person.display_name} required onChange={(e)=>setPerson({...person,display_name:e.target.value})}/></label><label>Mã nhân sự<input value={person.person_code} placeholder="Tự tạo nếu để trống" onChange={(e)=>setPerson({...person,person_code:e.target.value.toUpperCase()})}/></label><label>Bộ phận<select value={person.unit_code||''} onChange={(e)=>setPerson({...person,unit_code:e.target.value||null})}><option value="">—</option>{units.filter((u)=>u.active).map((u)=><option key={u.unit_code} value={u.unit_code}>{u.unit_name}</option>)}</select></label><label>Chức danh<input value={person.job_title||''} onChange={(e)=>setPerson({...person,job_title:e.target.value||null})}/></label><label className="org-check"><input type="checkbox" checked={person.active} onChange={(e)=>setPerson({...person,active:e.target.checked})}/> Đang làm việc</label><div className="org-form-actions"><button type="button" onClick={()=>setPerson(emptyPerson)}>Hủy</button><button type="submit" disabled={saving}>Lưu</button></div></form></div>:null}
    {!loading&&tab==='roles'?<div className="org-layout"><div className="org-card"><div className="org-card-title"><h2>Chức vụ quản lý</h2><button onClick={()=>setRole({...emptyRole})}>+ Thêm chức vụ</button></div><div className="org-role-list">{roles.map((item)=>{const assignment=currentAssignment.get(item.role_code);return <article key={item.role_code}><div><strong>{item.role_name}</strong><small>{item.role_code} · {item.unit_code?unitName.get(item.unit_code)||item.unit_code:'Toàn công ty'}</small></div><div className="org-current-holder"><span>Người hiện tại</span><b>{assignment?personName.get(assignment.person_code)||assignment.person_code:'Chưa bổ nhiệm'}</b></div><select defaultValue={assignment?.person_code||''} onChange={(e)=>{if(!e.target.value)return;void run(()=>appointRole(item.role_code,e.target.value,new Date().toISOString().slice(0,10)),`Đã bổ nhiệm ${personName.get(e.target.value)||e.target.value}`)}}><option value="">Đổi người giữ chức vụ…</option>{people.filter((p)=>p.active&&(!item.unit_code||p.unit_code===item.unit_code)).map((p)=><option key={p.person_code} value={p.person_code}>{p.display_name}</option>)}</select><button onClick={()=>setRole({...item})}>Sửa chức vụ</button></article>})}</div></div><form className="org-card org-form" onSubmit={(e)=>{e.preventDefault();const next={...role,role_code:role.role_code||codeFromName(role.role_name,'ROLE')};void run(()=>saveOrgRole(next),'Đã lưu chức vụ');setRole(emptyRole)}}><h2>{role.role_code?'Cập nhật chức vụ':'Thêm chức vụ'}</h2><label>Tên chức vụ<input value={role.role_name} required onChange={(e)=>setRole({...role,role_name:e.target.value})}/></label><label>Mã role<input value={role.role_code} placeholder="Tự tạo nếu để trống" onChange={(e)=>setRole({...role,role_code:e.target.value.toUpperCase()})}/></label><label>Bộ phận<select value={role.unit_code||''} onChange={(e)=>setRole({...role,unit_code:e.target.value||null})}><option value="">Toàn công ty</option>{units.filter((u)=>u.active).map((u)=><option key={u.unit_code} value={u.unit_code}>{u.unit_name}</option>)}</select></label><label className="org-check"><input type="checkbox" checked={role.active} onChange={(e)=>setRole({...role,active:e.target.checked})}/> Đang sử dụng</label><div className="org-form-actions"><button type="button" onClick={()=>setRole(emptyRole)}>Hủy</button><button type="submit" disabled={saving}>Lưu</button></div></form></div>:null}
    {!loading&&tab==='units'?<div className="org-layout"><div className="org-card"><div className="org-card-title"><h2>Sơ đồ bộ phận</h2><button onClick={()=>setUnit({...emptyUnit})}>+ Thêm bộ phận</button></div><div className="org-unit-list">{units.map((item)=><button key={item.unit_code} className={!item.active?'muted':''} onClick={()=>setUnit({...item})}><strong>{item.unit_name}</strong><span>{item.unit_type} · {item.parent_unit_code?unitName.get(item.parent_unit_code)||item.parent_unit_code:'Gốc'}</span></button>)}</div></div><form className="org-card org-form" onSubmit={(e)=>{e.preventDefault();const next={...unit,unit_code:unit.unit_code||codeFromName(unit.unit_name,'UNIT')};void run(()=>saveOrgUnit(next),'Đã lưu bộ phận');setUnit(emptyUnit)}}><h2>{unit.unit_code?'Cập nhật bộ phận':'Thêm bộ phận'}</h2><label>Tên bộ phận<input value={unit.unit_name} required onChange={(e)=>setUnit({...unit,unit_name:e.target.value})}/></label><label>Mã bộ phận<input value={unit.unit_code} placeholder="Tự tạo nếu để trống" onChange={(e)=>setUnit({...unit,unit_code:e.target.value.toUpperCase()})}/></label><label>Loại<select value={unit.unit_type} onChange={(e)=>setUnit({...unit,unit_type:e.target.value})}><option>COMPANY</option><option>TEAM</option><option>DEPARTMENT</option><option>PART</option></select></label><label>Đơn vị cấp trên<select value={unit.parent_unit_code||''} onChange={(e)=>setUnit({...unit,parent_unit_code:e.target.value||null})}><option value="">—</option>{units.filter((u)=>u.unit_code!==unit.unit_code).map((u)=><option key={u.unit_code} value={u.unit_code}>{u.unit_name}</option>)}</select></label><label>Thứ tự<input type="number" value={unit.sort_order} onChange={(e)=>setUnit({...unit,sort_order:Number(e.target.value)||0})}/></label><label className="org-check"><input type="checkbox" checked={unit.active} onChange={(e)=>setUnit({...unit,active:e.target.checked})}/> Đang sử dụng</label><div className="org-form-actions"><button type="button" onClick={()=>setUnit(emptyUnit)}>Hủy</button><button type="submit" disabled={saving}>Lưu</button></div></form></div>:null}
  </section>
}
